# The AskMalt Programming Language Grammar

Expr
	::=	Number
	|   Symbol
	|	String
	|	Quote
	|	Tuple
	|	Let
	|	If
	|	Cond
	|	Match
	|	Defun
	|	Lambda
	|	FCall
	;

Let ::= '(' "let" Symbol Expr ')' ;

If
	::= '(' "if" Expr Expr ')'
	|   '(' "if" Expr Expr Expr ')'
	;

Cond ::= '(' "cond" ('[' Expr Expr ']')+ ')' ;

Match ::= '(' "match" Expr ('[' Expr Expr ']')+ ')' ;

Defun ::= '(' "fun" Symbol '(' (Name)+ ')' (Expr)+ ')' ;

Lambda ::= '(' '\' '(' (Name)+ ')' (Expr)+ ')' ;

FCall ::= '(' (Expr)+ ')' ;

Quote
	::= '\''Expr
	|   '(' "quote" (Expr)+ ')'
	;

Tuple ::= '[' (Expr)+ ']' ;

Symbol := r"[^\0.]" ;

String := r"\"(.)+(\n)+(.)*(\n)+\"" ;

Number := r"/b+" ;

#True := "true"
#False := "false"

#Nil := "nil"